### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by midannii** [pku-sixing/WSDM2022-MHKD-TriKE#1]
Hi.

When I ran code below, 

```
$ python -u train.py --model_checkpoint thu-coai/CDial-GPT_LCCC-base --scheduler linear --pretrained --train_batch_size 8   --valid_steps 125000 --data_path data/toy_data.json  --gradient_accumulation_steps 4 --num_workers 0 --dataset_cache hke_verify_gpt_base --knowledge_cache hke_verify >> hke_verify_gpt_base2.txt
```

Then I faced this issue. 
```
2022-06-30 14:25:15.135352: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Running process -1
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Arguments: Namespace(gpt2=False, model_checkpoint='thu-coai/CDial-GPT_LCCC-base', from_step=-1, pretrained=True, external_knowledge_type='full_knowledge', max_length_of_text_knowledge=512, max_length_of_infobox_knowledge=512, max_length_of_graph_knowledge=512, data_path='data/toy_data.json', train_path='', valid_path='', dataset_cache='hke_verify_gpt_base', knowledge_cache='hke_verify', knowledge_mask='', log_file='debug', num_workers=0, n_epochs=20, train_batch_size=8, valid_batch_size=4, max_history=15, scheduler='linear', n_emd=768, lr=5e-05, eval_before_start=False, warmup_steps=5000, valid_steps=125000, gradient_accumulation_steps=4, max_norm=1.0, device='cpu', fp16='', local_rank=-1)
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Prepare tokenizer, pretrained model and optimizer - add special tokens for fine-tuning
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Some weights of OpenAIGPTLMHeadModel were not initialized from the model checkpoint at thu-coai/CDial-GPT_LCCC-base and are newly initialized because the shapes did not match:
- transformer.h.0.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.1.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.2.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.3.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.4.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.5.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.6.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.7.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.8.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.9.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.10.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
- transformer.h.11.attn.bias: found shape torch.Size([1, 1, 512, 512]) in the checkpoint and torch.Size([1, 1, 513, 513]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/iclserver5/anaconda3/envs/midan_RG/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Prepare datasets
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Build train and validation dataloaders
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Load tokenized dataset from cache at hke_verify_gpt_base_BertTokenizer
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:text 4
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:text 3
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:text 2
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:infobox 5
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:infobox 3
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:Tokenize and encode the dataset
INFO:/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py:infobox 2
Traceback (most recent call last):
  File "/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py", line 259, in <module>
    train()
  File "/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/train.py", line 129, in train
    train_loader, val_loader, train_sampler, valid_sampler = loader_class(args, tokenizer, logger)
  File "/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/od/inputters/inputter.py", line 268, in build_dataloaders
    datasets_src, datasets_tgt, knowledge_sets = get_data(args, tokenizer, args.data_path, args.dataset_cache,
  File "/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/od/inputters/inputter.py", line 63, in get_data
    knowledge_set_graph = generate_graph_knowledge_set(args.max_length_of_graph_knowledge,
  File "/home/iclserver5/Experiments/midannii/WSDM2022-MHKD-TriKE/od/inputters/inputter.py", line 225, in generate_graph_knowledge_set
    h_r_t = graph_vocab[int(triple)].split()
ValueError: invalid literal for int() with base 10: '从'

```

The setting process I ran is below 

1. Download model file from `thu-coai/CDial-GPT_LCCC-base` in huggingface 
2. Download dataset file from Google Drive(https://drive.google.com/file/d/19nBAbqRMjRv_Qf4gd1mvXS6mw690O1HO/view)

I definitely need your help !!!

**Comment by pku-sixing** [comment]
I think the reason is the wrong input file.

I can find this ' --data_path data/toy_data.json 'in your command. Unfortunately, the format of this toy file is not correct.

Please try to use the downloaded and processed JSON file.

**Comment by midannii** [comment]
Thank you for answering.

After I re-download dataset again, I am liberated from data issue :)
